// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHcslZXIjqu5DdO48YngHc6H7jLbKTJQ',
    appId: '1:220548640043:web:b898d3ffbf9c610796296e',
    messagingSenderId: '220548640043',
    projectId: 'servable-21605',
    authDomain: 'servable-21605.firebaseapp.com',
    storageBucket: 'servable-21605.firebasestorage.app',
    measurementId: 'G-SYR55EMTJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmf8Xp6UNtD3ro_8fYpdrnEz0_xbIKRa0',
    appId: '1:220548640043:android:b9999e998a7d41f796296e',
    messagingSenderId: '220548640043',
    projectId: 'servable-21605',
    storageBucket: 'servable-21605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUgvU8uqIHpUa9aatpZ_YZEj99Vkf13w',
    appId: '1:220548640043:ios:8ddb47a4fa37aaf196296e',
    messagingSenderId: '220548640043',
    projectId: 'servable-21605',
    storageBucket: 'servable-21605.firebasestorage.app',
    iosBundleId: 'com.example.servable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkUgvU8uqIHpUa9aatpZ_YZEj99Vkf13w',
    appId: '1:220548640043:ios:8ddb47a4fa37aaf196296e',
    messagingSenderId: '220548640043',
    projectId: 'servable-21605',
    storageBucket: 'servable-21605.firebasestorage.app',
    iosBundleId: 'com.example.servable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEHcslZXIjqu5DdO48YngHc6H7jLbKTJQ',
    appId: '1:220548640043:web:ab458745369590c596296e',
    messagingSenderId: '220548640043',
    projectId: 'servable-21605',
    authDomain: 'servable-21605.firebaseapp.com',
    storageBucket: 'servable-21605.firebasestorage.app',
    measurementId: 'G-M5MLXVVHZQ',
  );
}
